/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated/master-data'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as ApplySuccessAppNoRouteImport } from './routes/apply.success.$appNo'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApplySuccessAppNoRoute = ApplySuccessAppNoRouteImport.update({
  id: '/success/$appNo',
  path: '/success/$appNo',
  getParentRoute: () => ApplyRoute,
} as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/users': typeof AuthenticatedUsersRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/apply/success/$appNo': typeof ApplySuccessAppNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/users': typeof AuthenticatedUsersRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/apply/success/$appNo': typeof ApplySuccessAppNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/apply/success/$appNo': typeof ApplySuccessAppNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/applications'
    | '/audit'
    | '/dashboard'
    | '/master-data'
    | '/users'
    | '/applications/$id'
    | '/apply/success/$appNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/applications'
    | '/audit'
    | '/dashboard'
    | '/master-data'
    | '/users'
    | '/applications/$id'
    | '/apply/success/$appNo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/master-data'
    | '/_authenticated/users'
    | '/_authenticated/applications/$id'
    | '/apply/success/$appNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apply/success/$appNo': {
      id: '/apply/success/$appNo'
      path: '/success/$appNo'
      fullPath: '/apply/success/$appNo'
      preLoaderRoute: typeof ApplySuccessAppNoRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApplyRouteChildren {
  ApplySuccessAppNoRoute: typeof ApplySuccessAppNoRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplySuccessAppNoRoute: ApplySuccessAppNoRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
